version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: requirements/nginx/Dockerfile
    container_name: nginx
    ports:
      - "443:443"
    networks:
      - inception
    # volumes:
    #   - ./configs/default:/etc/nginx/sites-enabled
    #   - ./Cert:/etc/nginx/ssl/
    restart: on-failure

  mariadb:
    build:
      context: .
      dockerfile: requirements/mariadb/Dockerfile
    container_name: mariadb
    env_file:
      - .env
    ports:
      - "3306:3306"
    networks:
      - inception
    restart: on-failure
networks:
  inception: