version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "443:443"
    # volumes:
    #   - ./configs/default:/etc/nginx/sites-enabled
    #   - ./Cert:/etc/nginx/ssl/
    restart: always